development:
  adapter: mysql2
  encoding: utf8
  database: app_one_development
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true

test:
  adapter: mysql2
  encoding: utf8
  database: app_one_test
  username: root
  password: root
  pool: 5
  timeout: 5000
  
production:
  adapter: mysql2
  encoding: utf8
  database: app_one
  username: root
  password: [fill in on deploy]
  pool: 5
  timeout: 5000
  reconnect: true
